variable "region" {
  description = "AWS region for the ephemeral test cluster."
  type        = string
  default     = "eu-central-1"
}

variable "project_name" {
  description = "Name prefix applied to every resource and to the Name tags."
  type        = string
  default     = "kafka-test"
}

variable "instance_type" {
  description = <<-EOT
    EC2 instance type for the Kafka nodes. t3.small (2 vCPU / 2 GiB) is deliberately
    undersized: it exists to prove the Ansible role converges, not to size Kafka.
  EOT
  type        = string
  default     = "t3.small"
}

variable "root_volume_size" {
  description = "Root EBS volume size in GiB. Holds the OS, the Kafka install and the log dirs."
  type        = number
  default     = 30

  validation {
    condition     = var.root_volume_size >= 20
    error_message = "root_volume_size must be at least 20 GiB to fit the OS, JDK, Kafka and its log directories."
  }
}

variable "root_volume_type" {
  description = "Root EBS volume type."
  type        = string
  default     = "gp3"
}

variable "vpc_cidr" {
  description = "CIDR block for the dedicated test VPC."
  type        = string
  default     = "10.42.0.0/16"
}

variable "subnet_cidr" {
  description = "CIDR block for the public subnet holding the Kafka nodes."
  type        = string
  default     = "10.42.1.0/24"
}

variable "ssh_ingress_cidr" {
  description = <<-EOT
    Source CIDR permitted to reach SSH (TCP 22) on the Kafka nodes. Defaults to the
    whole internet: the machine running Ansible has a rotating public address, and
    pinning it to a /32 locks the run out mid-play as soon as that address changes.
    Authentication is key-only (ED25519, no password) and the environment is
    ephemeral. Narrow this where the operator address is stable.
  EOT
  type        = string
  default     = "0.0.0.0/0"

  validation {
    condition     = can(cidrhost(var.ssh_ingress_cidr, 0))
    error_message = "ssh_ingress_cidr must be a valid IPv4 CIDR, for example 203.0.113.10/32."
  }
}

variable "ssh_public_key_path" {
  description = <<-EOT
    Path to the ED25519 public key registered as the EC2 key pair. The matching private
    key is generated by scripts/create-ssh-key.sh outside Terraform and never enters
    Terraform state.
  EOT
  type        = string
  default     = "../.local/kafka-test.pub"
}

variable "ssh_username" {
  description = "Login user baked into the Ubuntu AMI."
  type        = string
  default     = "ubuntu"
}

variable "node_count" {
  description = <<-EOT
    Number of Kafka nodes. The assignment calls for exactly three: three combined
    broker+controller nodes give a KRaft quorum that tolerates one node failure.
  EOT
  type        = number
  default     = 3

  validation {
    condition     = var.node_count >= 3 && var.node_count % 2 == 1
    error_message = "node_count must be an odd number >= 3 so the KRaft controller quorum has a majority."
  }
}

variable "kafka_client_port" {
  description = "Kafka client/inter-broker listener port, opened only inside the security group."
  type        = number
  default     = 9092
}

variable "kafka_controller_port" {
  description = "KRaft controller listener port, opened only inside the security group."
  type        = number
  default     = 9093
}

variable "kafka_metrics_port" {
  description = "Prometheus JMX Exporter port, opened only inside the security group."
  type        = number
  default     = 9404
}
