#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
IDENTITY_FILE="${IDENTITY_FILE:-${REPO_ROOT}/.local/cluster-identity.yml}"
NODES="${NODES:-kafka-1 kafka-2 kafka-3}"

mkdir -p "$(dirname "${IDENTITY_FILE}")"
chmod 0700 "$(dirname "${IDENTITY_FILE}")"

if [[ -f "${IDENTITY_FILE}" ]]; then
  echo "Cluster identity already present at ${IDENTITY_FILE} - reusing it."
  echo "Regenerating it would orphan the formatted storage on every node."
  exit 0
fi

kafka_uuid() {
  python3 -c 'import base64,os;print(base64.urlsafe_b64encode(os.urandom(16)).decode().rstrip("="))'
}

umask 077
{
  echo "---"
  echo "# Generated by scripts/generate-cluster-identity.sh. Gitignored."
  echo "# These values are burned into KRaft metadata at format time and are immutable."
  echo "kafka_cluster_id: \"$(kafka_uuid)\""
  echo "kafka_controller_directory_ids:"
  for node in ${NODES}; do
    echo "  ${node}: \"$(kafka_uuid)\""
  done
} >"${IDENTITY_FILE}"

chmod 0600 "${IDENTITY_FILE}"

echo "Wrote ${IDENTITY_FILE}"
echo "Cluster ID: $(grep -oP '(?<=kafka_cluster_id: ").*(?=")' "${IDENTITY_FILE}")"
echo "Nodes: $(grep -c '^  kafka' "${IDENTITY_FILE}")"
