#!/usr/bin/env python3

from __future__ import annotations

import argparse
import json
import pathlib
import subprocess
import sys
from typing import Any

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent

def terraform_output(tf_dir: pathlib.Path) -> dict[str, Any]:
    result = subprocess.run(
        ["terraform", "output", "-json"],
        cwd=tf_dir,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        sys.exit(f"terraform output failed in {tf_dir}:\n{result.stderr.strip()}")
    return json.loads(result.stdout)

def yaml_quote(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'

def render(outputs: dict[str, Any], key_path: str) -> str:
    nodes = outputs["kafka_nodes"]["value"]
    ssh_user = outputs["ssh_username"]["value"]

    lines = [
        "---",
        "# Generated by scripts/render-inventory.py from terraform output -json.",
        "# Gitignored and rewritten on every apply - do not edit by hand.",
        "all:",
        "  children:",
        "    kafka:",
        "      hosts:",
    ]

    for name in sorted(nodes, key=lambda n: nodes[n]["node_id"]):
        node = nodes[name]
        lines += [
            f"        {name}:",
            f"          ansible_host: {yaml_quote(node['public_ip'])}",
            f"          kafka_node_id: {node['node_id']}",
            f"          kafka_private_ip: {yaml_quote(node['private_ip'])}",
            f"          kafka_private_dns: {yaml_quote(node['private_dns'])}",
        ]

    lines += [
        "      vars:",
        f"        ansible_user: {yaml_quote(ssh_user)}",
        f"        ansible_ssh_private_key_file: {yaml_quote(key_path)}",
        "        ansible_python_interpreter: /usr/bin/python3",
    ]
    return "\n".join(lines) + "\n"

def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--terraform-dir", default=str(REPO_ROOT / "terraform"))
    parser.add_argument("--output", default=str(REPO_ROOT / "inventory" / "generated.yml"))
    parser.add_argument("--ssh-key", default=str(REPO_ROOT / ".local" / "kafka-test"))
    args = parser.parse_args()

    outputs = terraform_output(pathlib.Path(args.terraform_dir))
    if "kafka_nodes" not in outputs:
        sys.exit("terraform output has no kafka_nodes - has terraform apply run?")

    destination = pathlib.Path(args.output)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(render(outputs, args.ssh_key))

    count = len(outputs["kafka_nodes"]["value"])
    print(f"Wrote {destination} with {count} Kafka nodes")

if __name__ == "__main__":
    main()
